# .github/workflows/notify-teams.yml
name: Notify Teams

on:
  workflow_call: # <-- Bu satır reusable workflow için şart

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest release version
        id: get_release
        run: |
          latest=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
          echo "LATEST_VERSION=$latest" >> $GITHUB_ENV

      - name: Send message to Microsoft Teams
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"text\": \"🚀 $GITHUB_REPOSITORY -  Yeni push yapıldı – Son sürüm: $LATEST_VERSION\"}" \
               https://ersas.webhook.office.com/webhookb2/fe02413e-2341-4e32-86fd-6999e8127e96@db0e3f28-856a-4556-99f7-821c8f3f2801/IncomingWebhook/caf57ca8d4474a748a261218f436d4ec/be96b88c-b537-4f44-a451-940e23713a58/V2mYY7y25Xh7daDyoP6SNQz2BePt-FjfDfv29Cv_-WYEE1
