# .github/workflows/notify-teams.yml
name: Notify Teams

on:
  workflow_call: # <-- Bu satır reusable workflow için şart
    secrets:
      TEAMS_WEBHOOK:
        required: true  # Bu secret dışarıdan gönderilmek zorunda

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Microsoft Teams
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"text\": \"🚀 Yeni bir push yapıldı: $GITHUB_REPOSITORY@$GITHUB_SHA\"}" \
               https://ersas.webhook.office.com/webhookb2/fe02413e-2341-4e32-86fd-6999e8127e96@db0e3f28-856a-4556-99f7-821c8f3f2801/IncomingWebhook/caf57ca8d4474a748a261218f436d4ec/be96b88c-b537-4f44-a451-940e23713a58/V2mYY7y25Xh7daDyoP6SNQz2BePt-FjfDfv29Cv_-WYEE1
