name: Tag sync
on:
  push:
    branches:
      - main

jobs:
  tag-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tag sync
        uses: francktrouillez/auto-tag-sync@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
